### PR TITLE
Fixed download when file storage is not local

### PR DESCRIPTION
**Pull request by renehanika**
The file download generates a 404 error when using a file storage which is not local like S3 - so I used the Storage download function instead of the response download.

### CODE REVIEW

**Comment by mafftor** [comment]
I'll take a look!

**Comment by rn1ee** [comment]
> I'll take a look!

Crop and resize images and rename folders have also some problems when using S3 as file storage - I will check this in the next days.

**Comment by mafftor** [comment]
Thanks! Let me test it out

**Comment by mafftor** [comment]
merged, thank you! <3

**Pull request merged**
